aws

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -29,12 +29,12 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-southeast-2
 
-      - name: Install Terraform
+      - name: Verify Terraform Installation
         run: |
-            curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
-            unzip -f terraform_1.5.0_linux_amd64.zip
-            sudo mv terraform /usr/local/bin/
-            terraform --version
+            ls -lah /usr/local/bin/terraform || echo "Terraform binary not found"
+            file /usr/local/bin/terraform || echo "Terraform file type unknown"
+            echo $PATH
+        
         
 
       - name: Initialize Terraform
