debug

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -43,17 +43,17 @@ jobs:
         
       - name: Move Terraform Correctly
         run: |
-            if [ -d "terraform" ]; then
-              sudo mv -f terraform/terraform /usr/local/bin/terraform
-            else
+            if [ -f "terraform" ]; then
               sudo mv -f terraform /usr/local/bin/terraform
+            else
+              echo "Terraform binary is missing after extraction!"
+              exit 1
             fi
             sudo chmod +x /usr/local/bin/terraform
             ls -lah /usr/local/bin/terraform || echo "Terraform still missing after move"
         
       - name: Force Update PATH
         run: |
-            echo "export PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
             echo "/usr/local/bin" >> $GITHUB_PATH
             source $GITHUB_ENV
             echo "Current PATH: $PATH"
