debug

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -28,6 +28,13 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-southeast-2
+
+      - name: Download Terraform
+        run: |
+            curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip || echo "Download failed"
+            ls -lah terraform_1.5.0_linux_amd64.zip || echo "Terraform ZIP file not found"
+            file terraform_1.5.0_linux_amd64.zip || echo "Terraform ZIP file is missing"
+        
           
       - name: Verify Terraform Download
         run: |
